#!/usr/bin/env bash

set -euo pipefail

pathDB="$HOME/projects/db/"

menu() {
    echo "What do you wish Mr. $USER!?"
    echo "w -> Show Me The Week(s)."
    echo "i -> Insert Data on The DataBase."
    echo "u -> Update to DataBase."
    echo "d -> Delete some data from The DataBase"
    echo "m -> Show Me The Data Analysis"
    echo "q -> Exit"
    echo -n "Choice an option: "
}

choice() {
    local todo="$1"

    case "$todo" in
        w | week)
            echo "Show Me The Week(s)"
            (
                cd "$pathDB" || exit 1
                sqlite3 < show.sql
            )
            ;;
        i | insert)
            echo "Insert Data"
            (
                cd "$pathDB" || exit 1
                sqlite3 < insert.sql
            )
            echo "Data Inserted"
            ;;
        u | update)
            echo "Update Data"
            (
                cd "$pathDB" || exit 1
                vim update.sql +4
                sqlite3 < update.sql
            )
            echo "Data Updated"
            ;;
        d | delete)
            echo "Delete something"
            (
                cd "$pathDB" || exit 1
                sqlite3 < delete.sql
            )
            ;;
        m | math)
            echo "Show The Data Analysis"
            (
                cd "$pathDB" || exit 1
                sqlite3 < math.sql
            )
            ;;
        q | quit)
            echo "Quit!"
            exit 0
            ;;
        *)
            echo "Invalid Input!"
            exit 1
            ;;
    esac
}

main() {
    if [[ "$#" -ne 0 ]]; then
        choice "$1"
    else
        menu
        read -r todo
        choice "$todo"
    fi
}

main "$@"
