#!/bin/bash

if [ "$#" -eq 0 ]; then
    echo "Argumentos Ausentes!"
    exit 1
fi

unzip $1.zip -d $1

if [ ! -d ./wallpaper/$1 ]; then
    echo "./wallaper/$1 doesn't exist!"
    echo "Let's go creat it!"
    mv -vf ./$1 ./wallpaper/$1
else
    rm -rf ./wallpaper/$1
    mv ./$1 ./wallpaper/$1
fi

rm $1.zip

rm *jpg *png *webp *jpeg
