#!/usr/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Missing parameter"
    exit 1
fi

dir="$HOME/code/$1/readme"

if [[ -e $dir ]]; then
    less "$dir"

elif [[ $1 = "db" ]] || [[ $1 = "sql" ]]; then
    less "$HOME/code/db/readme"

elif [[ $1 = "sh" ]] || [[ $1 = "bash" ]]; then
    less "$HOME/code/sh/readme"

else 
    echo "Doesn't exists README in $HOME/$1/"
    exit 1 
fi
