#!/usr/bin/bash

dir="$HOME/.local/bin/foo"

if [[ $# -eq 0 ]]; then
    echo "Argumentos Ausentes"
    exit 1
fi

if [[ -L $dir ]]; then
    rm $HOME/.local/bin/foo
fi

touch $1
chmod +x $1
ln -s $PWD/$1 $HOME/.local/bin/foo
vim $1
