#!/bin/bash

if [ "$#" -eq 0 ]; then
    echo "Argumentos Ausentes"
    exit 1
fi

if [ -L $HOME/.local/bin/foo ]; then
    rm $HOME/.local/bin/foo
fi

touch $1
chmod +x $1
ln -s $PWD/$1 $HOME/.local/bin/foo
vim $1
