#!/usr/bin/bash

dir="$HOME/.local/bin/foo"

if [[ $# -eq 0 ]]; then
    echo "Argumentos Ausentes"
    exit 1
fi

if [[ -L $dir ]]; then
    rm $HOME/.local/bin/foo
fi

touch $1
chmod +x $1
ln -s $PWD/$1 $HOME/.local/bin/foo

read -p "Deseja abrir o arquivo? sim ou não(s ou n)? " v
case $v in
    's' | 'S')
        helix "$1"
        ;;
    'n' | 'N')
        ;;
    *)
        echo "Entrada invalida"
        ;;
esac
