#!/usr/bin/bash

file="$HOME/.config/sway/config"

if [[ $# -eq 0 ]]; then
    sed -n '27p' "$file"
    
elif [[ "$#" -ne 3 ]]; then
    echo "Parâmetros insuficientes"
    exit 1
else
    sed -i "27s/$1/$2/" "$file"
    sed -i "27s/[0-9]\{1,2\}/$3/" "$file"
    sed -n '27p' "$file"
fi
