#!/usr/bin/env bash

set -euo pipefail

TRASH="$HOME/.local/share/Trash"
cd "$TRASH"
declare -A trash_info
sum_files=0

count_files() {
    for dir in *; do
        local number=$(find $dir -mindepth 1 | wc -l)
        trash_info["$dir"]=$number
        sum_files=$(($sum_files + $number))
    done
}

clean_trash() {
    echo -e "\033[33m----------- Clean Trash ------------\033[0m"
    for key in "${!trash_info[@]}"; do
        if [[ ${trash_info[$key]} -eq 0 ]]; then
            continue
        fi
        rm -rf ./$key/*
        trash_info[$key]=0
        sum_files=0
    done
}

show_trash() {
    echo -e "\033[33m----------- Show Trash -------------\033[0m"
    for key in $(printf "%s\n" "${!trash_info[@]}" | sort); do
        printf "\033[33mIn Trash/%s -> %d file(s)\033[0m\n" "$key" "${trash_info[$key]}"
    done

    local total_dirs=$((${#trash_info[@]}))
    printf "\n\033[33mNumber of dirs in Trash: $total_dirs\033[0m\n"
    printf "\033[33mTotal of files in Trash: $sum_files\033[0m\n"
    echo -e "\033[33m------------------------------------\033[0m"
}

main() {
    count_files
    show_trash
    echo
    clean_trash
    echo
    show_trash
}
main
