#!/usr/bin/env bash

ONE="$HOME/.cache/vim/swap/"
TWO="$HOME/.local/state/nvim/swap/"
THREE="$HOME/.local/state/nvim/undo/"
declare -a arr
totalFiles=0

menu() {
    printf "\n\033[33mWhat do you wish Mr. $USER?!\033[0m\n"
    echo -e "\033[33mr -> To remove\033[0m"
    echo -e "\033[33mn -> Does not remove\033[0m"

    printf "\n\033[33mChoise an option: \033[0m"
}

countFiles() {
    local paths=("$ONE" "$TWO" "$THREE")

    for i in "${paths[@]}"; do
        cd "$i"
        local count=$(ls -1 | wc -l)
        totalFiles=$(($totalFiles + $count))

        if (( $count != 0 )); then
            echo -e "\033[33mThere is '$count' to remove in: $PWD\033[0m"
            arr+=("$i")
        fi

        if (( $totalFiles == 0 )); then
                echo -e "\033[33mThere is nothing to remove!\033[0m"
                echo -e "\033[33mEverything's Clean Here!\033[0m"
                exit 0
        fi
    done
    echo -e "\033[31mTotal Files to Remove: $totalFiles\033[0m"
}

choice() {
    menu
    read -r todo
    case "$todo" in
        r)
            echo -e "\033[36mRemove Files\033[0m"

            for dir in "${!arr[@]}"; do
                echo -en "\033[36mCleaning The Directory: "
                echo -e "\033[36m${arr[$dir]}\033[0m"
                cd "${arr[$dir]}"
                rm ./*
            done
            unset arr
            totalFiles=0
            ;;
        n)
            echo -e "\033[36mNothing will be removed\033[0m"
            exit 0
            ;;
        *)
            echo -e "\n033[36mInvalid input\033[0m"
            exit 1
            ;;
    esac
}

main() {
    countFiles
    choice
    echo -e "\033[33mTotal Files to Remove: $totalFiles\033[0m"
}
main

